# Site settings
title: James Corey
email: jamescorey82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio page.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jamesrcorey
github_username:  mmjames04

# Build settings
markdown: kramdown
